[package]
name = "rust-synth-pad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
cpal = "0.15.2"
cuid2 = "0.1.2"
plotters = "0.3.5"
